### ISSUE TITLE
BUG CRASH when recording video (python train.py task=HumanoidAMP capture_video=True) --> render() got an unexpected keyword argument 'mode'

### ISSUE THREAD

**Issue by generush** [NVIDIA-Omniverse/IsaacGymEnvs#131]
Hello,

I've discovered IsaacGymEnvs can capture video (capture_video=True) for static viewers, but not dynamic ones.

IsaacGymEnvs immediately crashes when I run:

```bash
python train.py task=HumanoidAMP capture_video=True
```

Here is the error it produces:

```bash
Error executing job with overrides: ['task=HumanoidAMP', 'capture_video=True']
Traceback (most recent call last):
  File "train.py", line 190, in launch_rlg_hydra
    runner.run({
  File "/home/gene/code/NEURO/neuro-rl-sandbox/rl_games/rl_games/torch_runner.py", line 121, in run
    self.run_train(args)
  File "/home/gene/code/NEURO/neuro-rl-sandbox/rl_games/rl_games/torch_runner.py", line 102, in run_train
    agent.train()
  File "/home/gene/code/NEURO/neuro-rl-sandbox/IsaacGymEnvs/isaacgymenvs/learning/common_agent.py", line 120, in train
    self.obs = self.env_reset()
  File "/home/gene/code/NEURO/neuro-rl-sandbox/rl_games/rl_games/common/a2c_common.py", line 507, in env_reset
    obs = self.vec_env.reset()
  File "/home/gene/code/NEURO/neuro-rl-sandbox/IsaacGymEnvs/isaacgymenvs/utils/rlgames_utils.py", line 249, in reset
    return self.env.reset()
  File "/home/gene/anaconda3/envs/isaacgym/lib/python3.8/site-packages/gym/wrappers/record_video.py", line 58, in reset
    self.start_video_recorder()
  File "/home/gene/anaconda3/envs/isaacgym/lib/python3.8/site-packages/gym/wrappers/record_video.py", line 75, in start_video_recorder
    self.video_recorder.capture_frame()
  File "/home/gene/anaconda3/envs/isaacgym/lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py", line 157, in capture_frame
    frame = self.env.render(mode=render_mode)
TypeError: render() got an unexpected keyword argument 'mode'
```

I found this error, because I attempted to duplicate code from [HumanoidAMP](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/blob/3d2d5ed7ce71401db3063d8c339f4a800ce8709f/isaacgymenvs/tasks/amp/humanoid_amp_base.py#L392) to AnymalTerrain, but it also crashes and produces the same error.

Searching online, it seems people have faced various issues relating to gym versioning/compatibility, but not this specific issue. I haven't been able to figure out a solution after debugging for a day or two.

I would appreciate it if someone could take a look and hopefully spot a quick solution! Thank you very much for your help : )

**Comment by generush** [comment]
I did not mean to close this issue, as it is still unresolved. However, I wanted to include the package version in my environment:

```vim
# packages in environment at /home/gene/anaconda3/envs/isaacgym:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   1.2.0                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arrow                     1.2.3                    pypi_0    pypi
astroid                   2.15.3                   pypi_0    pypi
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     22.1.0                   pypi_0    pypi
autopep8                  1.7.0                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
backports-zoneinfo        0.2.1                    pypi_0    pypi
beautifulsoup4            4.11.2                   pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
blinker                   1.5                      pypi_0    pypi
bokeh                     2.4.3                    pypi_0    pypi
boto3                     1.26.63                  pypi_0    pypi
botocore                  1.29.63                  pypi_0    pypi
ca-certificates           2023.01.10           h06a4308_0  
cachetools                5.2.0                    pypi_0    pypi
certifi                   2022.12.7        py38h06a4308_0  
cffi                      1.15.1                   pypi_0    pypi
cftime                    1.6.2                    pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
codecov                   2.1.12                   pypi_0    pypi
colorcet                  3.0.1                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
comm                      0.1.2                    pypi_0    pypi
comparative-legged-rl     0.1.0                     dev_0    <develop>
contourpy                 1.0.5                    pypi_0    pypi
coverage                  7.1.0                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dash                      2.8.1                    pypi_0    pypi
dash-bootstrap-components 1.4.0                    pypi_0    pypi
dash-core-components      2.0.0                    pypi_0    pypi
dash-html-components      2.0.0                    pypi_0    pypi
dash-table                5.0.0                    pypi_0    pypi
dask                      2023.1.1                 pypi_0    pypi
datashader                0.14.4                   pypi_0    pypi
datashape                 0.5.2                    pypi_0    pypi
debugpy                   1.6.6                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
deepdiff                  6.2.3                    pypi_0    pypi
deeplake                  3.2.4                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.6                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
einops                    0.6.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
exceptiongroup            1.1.0                    pypi_0    pypi
executing                 0.8.3              pyhd3eb1b0_0  
fastjsonschema            2.16.2                   pypi_0    pypi
ffmpeg                    1.4                      pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
flake8                    6.0.0                    pypi_0    pypi
flask                     2.2.2                    pypi_0    pypi
flatbuffers               22.9.24                  pypi_0    pypi
fonttools                 4.37.4                   pypi_0    pypi
fqdn                      1.5.1                    pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2023.1.0                 pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
google-auth               2.12.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
gym                       0.23.1                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
holoviews                 1.14.9                   pypi_0    pypi
hub                       3.0.1                    pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
humbug                    0.2.7                    pypi_0    pypi
hydra-core                1.2.0                    pypi_0    pypi
idna                      3.4                      pypi_0    pypi
imageio                   2.22.1                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
iniconfig                 2.0.0                    pypi_0    pypi
ipykernel                 6.21.1                   pypi_0    pypi
ipython                   8.4.0            py38h06a4308_0  
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.4                    pypi_0    pypi
isaacgym                  1.0rc4                    dev_0    <develop>
isaacgymenvs              1.3.3                     dev_0    <develop>
isoduration               20.11.0                  pypi_0    pypi
isort                     5.12.0                   pypi_0    pypi
itsdangerous              2.1.2                    pypi_0    pypi
jedi                      0.18.1           py38h06a4308_1  
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  1.0.1                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonpickle                3.0.0                    pypi_0    pypi
jsonpointer               2.3                      pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter-bokeh             3.0.5                    pypi_0    pypi
jupyter-client            8.0.2                    pypi_0    pypi
jupyter-core              5.2.0                    pypi_0    pypi
jupyter-events            0.6.3                    pypi_0    pypi
jupyter-server            2.2.1                    pypi_0    pypi
jupyter-server-terminals  0.4.4                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.5                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
lazy-object-proxy         1.9.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
llvmlite                  0.39.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
loguru                    0.6.0                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markdown-it-py            2.1.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.1                    pypi_0    pypi
matplotlib-inline         0.1.6            py38h06a4308_0  
mccabe                    0.7.0                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
mock                      5.0.1                    pypi_0    pypi
moviepy                   1.0.3                    pypi_0    pypi
mpmath                    1.2.1                    pypi_0    pypi
msgpack                   1.0.4                    pypi_0    pypi
multipledispatch          0.6.0                    pypi_0    pypi
multiprocess              0.70.14                  pypi_0    pypi
mypy                      0.982                    pypi_0    pypi
mypy-extensions           0.4.3                    pypi_0    pypi
nbclassic                 0.5.1                    pypi_0    pypi
nbclient                  0.7.2                    pypi_0    pypi
nbconvert                 7.2.9                    pypi_0    pypi
nbformat                  5.7.3                    pypi_0    pypi
nbsmoke                   0.6.0                    pypi_0    pypi
ncurses                   6.3                  h5eee18b_3  
nest-asyncio              1.5.6                    pypi_0    pypi
netcdf4                   1.6.2                    pypi_0    pypi
netron                    6.1.1                    pypi_0    pypi
networkx                  3.0                      pypi_0    pypi
ninja                     1.10.2.4                 pypi_0    pypi
ninja-base                1.10.2               hd09550d_5  
nose                      1.3.7                    pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numba                     0.56.4                   pypi_0    pypi
numcodecs                 0.11.0                   pypi_0    pypi
numpy                     1.23.4                   pypi_0    pypi
oauthlib                  3.2.1                    pypi_0    pypi
omegaconf                 2.2.3                    pypi_0    pypi
onnx                      1.12.0                   pypi_0    pypi
onnxruntime               1.12.1                   pypi_0    pypi
opencv-python             4.7.0.72                 pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0  
ordered-set               4.1.0                    pypi_0    pypi
orjson                    3.8.5                    pypi_0    pypi
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
panel                     0.14.3                   pypi_0    pypi
param                     1.12.3                   pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.3.0                    pypi_0    pypi
path                      16.6.0                   pypi_0    pypi
path-py                   12.5.0                   pypi_0    pypi
pathos                    0.3.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.2.0                    pypi_0    pypi
pip                       22.2.2           py38h06a4308_0  
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.2                    pypi_0    pypi
plotly                    5.13.0                   pypi_0    pypi
pluggy                    1.0.0                    pypi_0    pypi
pox                       0.3.2                    pypi_0    pypi
ppft                      1.7.6.6                  pypi_0    pypi
proglog                   0.1.10                   pypi_0    pypi
prometheus-client         0.16.0                   pypi_0    pypi
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
protobuf                  3.19.6                   pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pyarrow                   11.0.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.10.0                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyct                      0.5.0                    pypi_0    pypi
pydeck                    0.8.0                    pypi_0    pypi
pyflakes                  3.0.1                    pypi_0    pypi
pygments                  2.14.0                   pypi_0    pypi
pyjwt                     2.6.0                    pypi_0    pypi
pylint                    2.17.2                   pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pytest                    7.2.1                    pypi_0    pypi
python                    3.8.13               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.20.1                   pypi_0    pypi
python-json-logger        2.0.4                    pypi_0    pypi
pytz                      2022.6                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyvirtualdisplay          3.0                      pypi_0    pypi
pyviz-comms               2.2.1                    pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     25.0.0                   pypi_0    pypi
ray                       1.13.0                   pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
requests                  2.28.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rich                      13.3.1                   pypi_0    pypi
rl-games                  1.6.0                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
rsl-rl                    1.0.2                     dev_0    <develop>
s3transfer                0.6.0                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.9.2                    pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
sentry-sdk                1.9.10                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                59.5.0                   pypi_0    pypi
shapely                   2.0.1                    pypi_0    pypi
shortuuid                 1.0.9                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
sklearn                   0.0.post1                pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.3               h5082296_0  
stack_data                0.2.0              pyhd3eb1b0_0  
streamlit                 1.17.0                   pypi_0    pypi
streamz                   0.6.4                    pypi_0    pypi
sympy                     1.11.1                   pypi_0    pypi
tenacity                  8.1.0                    pypi_0    pypi
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
termcolor                 2.0.1                    pypi_0    pypi
termcolor-whl             1.1.2                    pypi_0    pypi
terminado                 0.17.1                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2023.2.3                 pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tomlkit                   0.11.7                   pypi_0    pypi
toolz                     0.12.0                   pypi_0    pypi
torch                     1.12.0+cu116             pypi_0    pypi
torch-summary             1.4.5                    pypi_0    pypi
torchaudio                0.12.0+cu116             pypi_0    pypi
torchvision               0.13.0+cu116             pypi_0    pypi
torchviz                  0.0.2                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.9.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
tzdata                    2022.7                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
uri-template              1.2.0                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
virtualenv                20.16.5                  pypi_0    pypi
wandb                     0.12.11                  pypi_0    pypi
watchdog                  2.2.1                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webcolors                 1.12                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.5.1                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        4.0.5                    pypi_0    pypi
wrapt                     1.15.0                   pypi_0    pypi
xarray                    2023.1.0                 pypi_0    pypi
xz                        5.2.6                h5eee18b_0  
yaspin                    2.2.0                    pypi_0    pypi
zict                      2.2.0                    pypi_0    pypi
zipp                      3.9.0                    pypi_0    pypi
zlib                      1.2.12               h5eee18b_3

**Comment by zzzark** [comment]
@generush Hi. I have encountered the same issue. After lots of debugging I find that it is not a bug in rl_games or gym or any other packages, but indeed in humanoid_amp_base.py.

So to fix this issue just simply change the following lines in humanoid_amp_base.py in line 392 from:

```python
def render(self):
    if self.viewer and self.camera_follow:
        self._update_camera()

    super().render()
    return
```

to 

```python
def render(self, mode="rgb_array"):
    if self.viewer and self.camera_follow:
        self._update_camera()

    return super().render(mode)
```

Hope this help.
