### ISSUE TITLE
No module named 'isaacgymenvs.tasks.factory'

### ISSUE THREAD

**Issue by nooshin-kohli** [NVIDIA-Omniverse/IsaacGymEnvs#142]
Hi everyone! 
I am trying to test codes but after running I get this error:

Traceback (most recent call last):
  File "isaac_gym.py", line 15, in <module>
    force_render=False
  File "/home/lenovo/miniconda3/envs/rlgpu/lib/python3.7/site-packages/isaacgymenvs/__init__.py", line 27, in make
    from isaacgymenvs.utils.rlgames_utils import get_rlgames_env_creator
  File "/home/lenovo/miniconda3/envs/rlgpu/lib/python3.7/site-packages/isaacgymenvs/utils/rlgames_utils.py", line 40, in <module>
    from isaacgymenvs.tasks import isaacgym_task_map
  File "/home/lenovo/miniconda3/envs/rlgpu/lib/python3.7/site-packages/isaacgymenvs/tasks/__init__.py", line 34, in <module>
    from .factory.factory_task_gears import FactoryTaskGears
ModuleNotFoundError: No module named 'isaacgymenvs.tasks.factory'

I followed the installations but here is the error. Can you help me?

**Comment by nooshin-kohli** [comment]
It worked out by cloning this repo in the same directory as isaacgym.
