### ISSUE TITLE
ModuleNotFoundError: No module named 'isaacgymenvs'

### ISSUE THREAD

**Issue by HiuhiuWong** [NVIDIA-Omniverse/IsaacGymEnvs#192]
when I run the code: python ./isaacgymenvs/train.py task=Ant (I was at the path:/IsaacGymEnvs)
I have the error as below:
when I run the code: python train.py task=Ant (I was at the path:/IsaacGymEnvs/isaacgymenvs)
I have the same error as below:
/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
Importing module 'gym_37' (/home/felicityw/ISSAC/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/felicityw/ISSAC/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
Error executing job with overrides: ['task=Ant']
Traceback (most recent call last):
  File "./isaacgymenvs/train.py", line 219, in <module>
    launch_rlg_hydra()
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/main.py", line 99, in decorated_main
    config_name=config_name,
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/utils.py", line 401, in _run_hydra
    overrides=overrides,
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/utils.py", line 458, in _run_app
    lambda: hydra.run(
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    overrides=overrides,
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/felicityw/miniconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "./isaacgymenvs/train.py", line 80, in launch_rlg_hydra
    from isaacgymenvs.pbt.pbt import PbtAlgoObserver, initial_pbt_check
ModuleNotFoundError: No module named 'isaacgymenvs'

**Comment by qqsq12321** [comment]
i got the same error, have u fixed it now? pls let me know!!!
