### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by hamidh1** [NVIDIA-Omniverse/IsaacGymEnvs#211]
I am trying to run the play.py file:https://github.com/leggedrobotics/legged_gym/blob/master/legged_gym/scripts/play.py        I have this error when i run tthis file.  How to resolve this issue? Please someone advise. Will be grateful.

Here is the error, below:
~/Desktop/RARL$ /home/hmd/anaconda3/envs/rlgpu/bin/python /home/hmd/Desktop/RARL/isaacgym/legged_gym-master/legged_gym/scripts/play.py
Importing module 'gym_38' (/home/hmd/Desktop/RARL/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/hmd/Desktop/RARL/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 2.2.1+cu121
Device count 1
/home/hmd/Desktop/RARL/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/hmd/.cache/torch_extensions/py38_cu121 as PyTorch extensions root...
Emitting ninja build file /home/hmd/.cache/torch_extensions/py38_cu121/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
Setting seed: 1
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
/home/hmd/anaconda3/envs/rlgpu/lib/python3.8/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
'train_cfg' provided -> Ignoring 'name=anymal_c_flat'
Traceback (most recent call last):
  File "/home/hmd/Desktop/RARL/isaacgym/legged_gym-master/legged_gym/scripts/play.py", line 121, in <module>
    play(args)
  File "/home/hmd/Desktop/RARL/isaacgym/legged_gym-master/legged_gym/scripts/play.py", line 58, in play
    ppo_runner, train_cfg = task_registry.make_alg_runner(env=env, name=args.task, args=args, train_cfg=train_cfg)
  File "/home/hmd/Desktop/RARL/isaacgym/legged_gym-master/legged_gym/utils/task_registry.py", line 147, in make_alg_runner
    runner = OnPolicyRunner(env, train_cfg_dict, log_dir, device=args.rl_device)
  File "/home/hmd/Desktop/RARL/isaacgym/rsl_rl/rsl_rl/runners/on_policy_runner.py", line 29, in __init__
    obs, extras = self.env.get_observations()
ValueError: too many values to unpack (expected 2)

**Comment by hamidh1** [comment]
![error](https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/assets/129813299/424fcc98-ad0e-4e68-9b9d-04c5d04c7214)
