### ISSUE TITLE
AttributeError: 'isaacgym._bindings.linux-x86_64.gym_37.AssetOptions' object has no attribute 'enable_gyroscopic_forces'

### ISSUE THREAD

**Issue by nicholas0717** [NVIDIA-Omniverse/IsaacGymEnvs#61]
I got a trouble when I ran `python train.py Task=FactoryTaskNutBoltPlace`. It showed AttributeError: 'isaacgym._bindings.linux-x86_64.gym_37.AssetOptions' object has no attribute 'enable_gyroscopic_forces'. The full output is below:

`Importing module 'gym_37' (/home/cai/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/cai/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
train.py:49: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_name="config", config_path="./cfg")
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:415: UserWarning: In config: Invalid overriding of hydra/job_logging:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
PyTorch version 1.8.1
Device count 1
/home/cai/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/cai/.cache/torch_extensions as PyTorch extensions root...
Emitting ninja build file /home/cai/.cache/torch_extensions/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
/home/cai/isaacgym/python/isaacgym/torch_utils.py:135: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def get_axis_params(value, axis_idx, x_value=0., dtype=np.float, n_dims=3):
2022-07-17 01:10:26,842 - INFO - logger - logger initialized
<unknown>:6: DeprecationWarning: invalid escape sequence \*
Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/utils/tensorboard/__init__.py:3: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, '__version__') or LooseVersion(tensorboard.__version__) < LooseVersion('1.15'):
task: 
    name: FactoryTaskGears
    physics_engine: physx
    sim: 
        use_gpu_pipeline: True
        up_axis: z
        dt: 0.016667
        gravity: [0.0, 0.0, -9.81]
    env: 
        numEnvs: 128
        numObservations: 32
        numActions: 12
    randomize: 
        joint_noise: 0.0
        initial_state: random
        gears_bias_y: -0.1
        gears_bias_z: 0.0
        gears_noise_xy: 0.05
    rl: 
        max_episode_length: 1024
train: 
    params: 
        seed: 42
        algo: 
            name: a2c_continuous
        model: 
            name: continuous_a2c_logstd
        network: 
            name: actor_critic
            separate: False
            space: 
                continuous: 
                    mu_activation: None
                    sigma_activation: None
                    mu_init: 
                        name: default
                    sigma_init: 
                        name: const_initializer
                        val: 0
                    fixed_sigma: True
            mlp: 
                units: [256, 128, 64]
                activation: elu
                d2rl: False
                initializer: 
                    name: default
                regularizer: 
                    name: None
        load_checkpoint: False
        load_path: 
        config: 
            name: FactoryTaskGears
            full_experiment_name: FactoryTaskGears
            env_name: rlgpu
            multi_gpu: False
            ppo: True
            mixed_precision: True
            normalize_input: True
            normalize_value: True
            value_bootstrap: True
            num_actors: 128
            reward_shaper: 
                scale_value: 1.0
            normalize_advantage: True
            gamma: 0.99
            tau: 0.95
            learning_rate: 0.0001
            lr_schedule: fixed
            schedule_type: standard
            kl_threshold: 0.016
            score_to_win: 20000
            max_epochs: 8192
            save_best_after: 50
            save_frequency: 100
            print_stats: True
            grad_norm: 1.0
            entropy_coef: 0.0
            truncate_grads: False
            e_clip: 0.2
            horizon_length: 32
            minibatch_size: 512
            mini_epochs: 8
            critic_coef: 2
            clip_value: True
            seq_len: 4
            bounds_loss_coef: 0.0001
task_name: FactoryTaskGears
experiment: 
num_envs: 
seed: 42
torch_deterministic: False
max_iterations: 
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: False
checkpoint: 
multi_gpu: False
wandb_activate: False
wandb_group: 
wandb_name: FactoryTaskGears
wandb_entity: 
wandb_project: isaacgymenvs
capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True
headless: False
Setting seed: 42
self.seed = 42
Started to train
Exact experiment name requested from command line: FactoryTaskGears
/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/gym/spaces/box.py:112: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")
Not connected to PVD
+++ Using GPU PhysX
Physics Engine: PhysX
Physics Device: cuda:0
GPU Pipeline: enabled
Error executing job with overrides: ['task=FactoryTaskGears', 'headless=False']
Traceback (most recent call last):
  File "train.py", line 181, in launch_rlg_hydra
    'sigma' : None
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 120, in run
    self.run_train(args)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 98, in run_train
    agent = self.algo_factory.create(self.algo_name, base_name='run', params=self.params)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/common/object_factory.py", line 15, in create
    return builder(**kwargs)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/torch_runner.py", line 39, in <lambda>
    self.algo_factory.register_builder('a2c_continuous', lambda **kwargs : a2c_continuous.A2CAgent(**kwargs))
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/algos_torch/a2c_continuous.py", line 16, in __init__
    a2c_common.ContinuousA2CBase.__init__(self, base_name, params)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/common/a2c_common.py", line 999, in __init__
    A2CBase.__init__(self, base_name, params)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/common/a2c_common.py", line 100, in __init__
    self.vec_env = vecenv.create_vec_env(self.env_name, self.num_actors, **self.env_config)
  File "/home/cai/anaconda3/envs/rlgpu/lib/python3.7/site-packages/rl_games/common/vecenv.py", line 222, in create_vec_env
    return vecenv_config[vec_env_name](config_name, num_actors, **kwargs)
  File "train.py", line 125, in <lambda>
    lambda config_name, num_actors, **kwargs: RLGPUEnv(config_name, num_actors, **kwargs))
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/utils/rlgames_utils.py", line 153, in __init__
    self.env = env_configurations.configurations[config_name]['env_creator'](**kwargs)
  File "train.py", line 111, in create_env_thunk
    **kwargs,
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/__init__.py", line 55, in make
    return create_rlgpu_env()
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/utils/rlgames_utils.py", line 85, in create_rlgpu_env
    force_render=force_render,
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_task_gears.py", line 54, in __init__
    super().__init__(cfg, rl_device, sim_device, graphics_device_id, headless, virtual_screen_capture, force_render)
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_env_gears.py", line 55, in __init__
    super().__init__(cfg, rl_device, sim_device, graphics_device_id, headless, virtual_screen_capture, force_render)
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_base.py", line 64, in __init__
    super().__init__(cfg, rl_device, sim_device, graphics_device_id, headless, virtual_screen_capture, force_render)  # create_sim() is called here
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/base/vec_task.py", line 215, in __init__
    self.create_sim()
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_base.py", line 115, in create_sim
    self.create_envs()  # defined in subclass
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_env_gears.py", line 85, in create_envs
    franka_asset, table_asset = self.import_franka_assets()
  File "/home/cai/isaacgym/IsaacGymEnvs/isaacgymenvs/tasks/factory/factory_base.py", line 154, in import_franka_assets
    franka_options.enable_gyroscopic_forces = True
AttributeError: 'isaacgym._bindings.linux-x86_64.gym_37.AssetOptions' object has no attribute 'enable_gyroscopic_forces'`

How can I solve this problem? I really need your help. Looking forward your reply. Thanks!

**Comment by nicholas0717** [comment]
Have fixed it. Just download the preview 4 of isaacgym. Preview 3 didn't support Factory.
