### ISSUE TITLE
import ERROR

### ISSUE THREAD

**Issue by junghs1040** [NVIDIA-Omniverse/IsaacGymEnvs#71]
Hi i got an error 
i want to try task=Cartpole, but the following error occured

Importing module 'gym_38' (/home/seok2/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/seok2/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:251: UserWarning: In 'config': Defaults list is missing `_self_`. See https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order for more information
  warnings.warn(msg, UserWarning)
/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/defaults_list.py:412: UserWarning: In config: Invalid overriding of hydra/job_logging:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  deprecation_warning(msg)
PyTorch version 1.10.0+cu113
Device count 1
/home/seok2/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/seok2/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Emitting ninja build file /home/seok2/.cache/torch_extensions/py38_cu113/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
/home/seok2/isaacgym/python/isaacgym/torch_utils.py:135: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def get_axis_params(value, axis_idx, x_value=0., dtype=np.float, n_dims=3):
Error executing job with overrides: ['task=Cartpole']
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 188, in <module>
    launch_rlg_hydra()
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 294, in run_and_report
    raise ex
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/home/seok2/anaconda3/envs/rlstudy/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "train.py", line 51, in launch_rlg_hydra
    from isaacgymenvs.utils.rlgames_utils import RLGPUEnv, RLGPUAlgoObserver, get_rlgames_env_creator
  File "/home/seok2/IsaacGymEnvs/isaacgymenvs/utils/rlgames_utils.py", line 36, in <module>
    from tasks import isaacgym_task_map
  File "/home/seok2/.local/share/Trash/files/IsaacGymEnvs.2/isaacgymenvs/tasks/__init__.py", line 30, in <module>
    from .ant import Ant
  File "/home/seok2/.local/share/Trash/files/IsaacGymEnvs.2/isaacgymenvs/tasks/ant.py", line 38, in <module>
    from isaacgymenvs.tasks.base.vec_task import VecTask
  File "/home/seok2/IsaacGymEnvs/isaacgymenvs/tasks/__init__.py", line 31, in <module>
    from tasks.ant import Ant
ImportError: cannot import name 'Ant' from partially initialized module 'tasks.ant' (most likely due to a circular import) (/home/seok2/.local/share/Trash/files/IsaacGymEnvs.2/isaacgymenvs/tasks/ant.py)

**Comment by ChengEeee** [comment]
I have the same issue.Have you solved it？

**Comment by junghs1040** [comment]
> I have the same issue.Have you solved it？

Yes i solved 
I was using conda environment and i did pip install - e in base environment

I did pip install -e again in right conda environment again and it worked!
